In [1]:
import pandas as pd

df_travel = pd.read_csv('data1/tn_travel_여행_A.csv')
df_place = pd.read_csv('data1/tn_visit_area_info_방문지정보_A.csv')
df_traveler = pd.read_csv('data1/tn_traveller_master_여행객 Master_A.csv')

In [2]:
df = pd.merge(df_place, df_travel, on='TRAVEL_ID', how='left')
df = pd.merge(df, df_traveler, on='TRAVELER_ID', how='left')

df.head(3)

,VISIT_AREA_ID,TRAVEL_ID,VISIT_ORDER,VISIT_AREA_NM,VISIT_START_YMD,VISIT_END_YMD,ROAD_NM_ADDR,LOTNO_ADDR,X_COORD,Y_COORD,...,TRAVEL_STYL_7,TRAVEL_STYL_8,TRAVEL_STATUS_RESIDENCE,TRAVEL_STATUS_DESTINATION,TRAVEL_STATUS_ACCOMPANY,TRAVEL_STATUS_YMD,TRAVEL_MOTIVE_1,TRAVEL_MOTIVE_2,TRAVEL_MOTIVE_3,TRAVEL_COMPANIONS_NUM
0,2210300006,a_a015688,5,프로방스마을,2022-10-30,2022-10-30,경기 파주시 탄현면 새오리로 77,경기 파주시 탄현면 성동리 82-1,126.685239,37.790405,...,6.0,6.0,경기도,경기,나홀로 여행,2022-10-30~2022-10-31,1.0,7.0,10.0,0.0
1,2208050001,a_a000164,1,친구/친지집,2022-08-05,2022-08-05,NaN,경기도 안산시 단원구 와동,NaN,NaN,...,3.0,5.0,경기도,경기,2인 여행(가족 외),2022-08-05~2022-08-06,3.0,2.0,1.0,1.0
2,2210030002,a_a004293,2,병점역 1호선,2022-10-03,2022-10-03,경기 화성시 떡전골로 97,경기 화성시 진안동 824-1,127.033200,37.206753,...,7.0,2.0,경기도,경기,나홀로 여행,2022-10-03~2022-10-03,6.0,2.0,1.0,0.0

In [9]:
df[df['TRAVEL_ID'] == 'a_a015688']

,VISIT_AREA_ID,TRAVEL_ID,VISIT_ORDER,VISIT_AREA_NM,VISIT_START_YMD,VISIT_END_YMD,ROAD_NM_ADDR,LOTNO_ADDR,X_COORD,Y_COORD,...,TRAVEL_STYL_7,TRAVEL_STYL_8,TRAVEL_STATUS_RESIDENCE,TRAVEL_STATUS_DESTINATION,TRAVEL_STATUS_ACCOMPANY,TRAVEL_STATUS_YMD,TRAVEL_MOTIVE_1,TRAVEL_MOTIVE_2,TRAVEL_MOTIVE_3,TRAVEL_COMPANIONS_NUM
0,2210300006,a_a015688,5,프로방스마을,2022-10-30,2022-10-30,경기 파주시 탄현면 새오리로 77,경기 파주시 탄현면 성동리 82-1,126.685239,37.790405,...,6.0,6.0,경기도,경기,나홀로 여행,2022-10-30~2022-10-31,1.0,7.0,10.0,0.0
7060,2210300002,a_a015688,7,다온무인텔,2022-10-30,2022-10-31,경기 파주시 탄현면 성동로 7-25,경기 파주시 탄현면 성동리 666-3,126.686597,37.780606,...,6.0,6.0,경기도,경기,나홀로 여행,2022-10-30~2022-10-31,1.0,7.0,10.0,0.0
8788,2210300005,a_a015688,4,헤이리예술마을,2022-10-30,2022-10-30,NaN,경기 파주시 탄현면 법흥리 1652-239,126.698953,37.788174,...,6.0,6.0,경기도,경기,나홀로 여행,2022-10-30~2022-10-31,1.0,7.0,10.0,0.0
10467,2210310002,a_a015688,9,집,2022-10-31,2022-11-01,NaN,NaN,NaN,NaN,...,6.0,6.0,경기도,경기,나홀로 여행,2022-10-30~2022-10-31,1.0,7.0,10.0,0.0
13659,2210310001,a_a015688,8,아이노스 출판단지점,2022-10-31,2022-10-31,경기 파주시 문발로 142,경기 파주시 문발동 531-1,126.686457,37.707170,...,6.0,6.0,경기도,경기,나홀로 여행,2022-10-30~2022-10-31,1.0,7.0,10.0,0.0
18718,2210300004,a_a015688,3,롯데프리미엄아울렛 파주점,2022-10-30,2022-10-30,경기 파주시 문발로 284,경기 파주시 문발동 644,126.692643,37.718115,...,6.0,6.0,경기도,경기,나홀로 여행,2022-10-30~2022-10-31,1.0,7.0,10.0,0.0
28239,2210300003,a_a015688,2,지혜의숲,2022-10-30,2022-10-30,경기 파주시 회동길 145,경기 파주시 문발동 524-3,126.687060,37.708354,...,6.0,6.0,경기도,경기,나홀로 여행,2022-10-30~2022-10-31,1.0,7.0,10.0,0.0

In [3]:
df_filter = df[df['TRAVEL_MISSION_CHECK'].notna()].copy()
df_filter.loc[:, 'TRAVEL_MISSION_INT'] = df_filter['TRAVEL_MISSION_CHECK'].str.split(';').str[0].astype(int)
df_filter

,VISIT_AREA_ID,TRAVEL_ID,VISIT_ORDER,VISIT_AREA_NM,VISIT_START_YMD,VISIT_END_YMD,ROAD_NM_ADDR,LOTNO_ADDR,X_COORD,Y_COORD,...,TRAVEL_STYL_8,TRAVEL_STATUS_RESIDENCE,TRAVEL_STATUS_DESTINATION,TRAVEL_STATUS_ACCOMPANY,TRAVEL_STATUS_YMD,TRAVEL_MOTIVE_1,TRAVEL_MOTIVE_2,TRAVEL_MOTIVE_3,TRAVEL_COMPANIONS_NUM,TRAVEL_MISSION_INT
0,2210300006,a_a015688,5,프로방스마을,2022-10-30,2022-10-30,경기 파주시 탄현면 새오리로 77,경기 파주시 탄현면 성동리 82-1,126.685239,37.790405,...,6.0,경기도,경기,나홀로 여행,2022-10-30~2022-10-31,1.0,7.0,10.0,0.0,5
1,2208050001,a_a000164,1,친구/친지집,2022-08-05,2022-08-05,NaN,경기도 안산시 단원구 와동,NaN,NaN,...,5.0,경기도,경기,2인 여행(가족 외),2022-08-05~2022-08-06,3.0,2.0,1.0,1.0,22
2,2210030002,a_a004293,2,병점역 1호선,2022-10-03,2022-10-03,경기 화성시 떡전골로 97,경기 화성시 진안동 824-1,127.033200,37.206753,...,2.0,경기도,경기,나홀로 여행,2022-10-03~2022-10-03,6.0,2.0,1.0,0.0,28
3,2208200003,a_a000491,12,더현대서울,2022-08-20,2022-08-20,서울 영등포구 여의대로 108,서울 영등포구 여의도동 22,126.928446,37.525872,...,7.0,울산광역시,서울,2인 가족 여행,2022-08-19~2022-08-20,1.0,3.0,7.0,1.0,6
4,2208110007,a_a000172,13,강릉중앙시장,2022-08-11,2022-08-11,강원 강릉시 금성로 21,강원 강릉시 성남동 50,128.898624,37.754025,...,4.0,광주광역시,서울,나홀로 여행,2022-08-10~2022-08-13,1.0,7.0,2.0,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30149,2210220005,a_a008553,5,집,2022-10-22,2022-10-23,NaN,NaN,NaN,NaN,...,3.0,서울특별시,경기,나홀로 여행,2022-10-22~2022-10-22,2.0,1.0,NaN,0.0,6
30150,2208280003,a_a001505,6,카페아쁠뤼스,2022-08-28,2022-08-28,경기 가평군 청평면 신청평로 107,경기 가평군 청평면 대성리 3-5,127.406939,37.728238,...,4.0,서울특별시,경기,3인 이상 여행(가족 외),2022-08-27~2022-08-28,1.0,3.0,7.0,7.0,5
30151,2210290005,a_a013660,4,국립중앙박물관,2022-10-29,2022-10-29,서울 용산구 서빙고로 137,서울 용산구 용산동6가 168-6,126.980203,37.523847,...,6.0,경기도,서울,나홀로 여행,2022-10-29~2022-10-30,1.0,7.0,8.0,0.0,3
30152,2208060008,a_a000019,7,송도달빛축제공원,2022-08-06,2022-08-06,인천 연수구 센트럴로 350,인천 연수구 송도동 26-1,126.634896,37.407218,...,3.0,서울특별시,인천,3인 이상 여행(가족 외),2022-08-06~2022-08-07,7.0,5.0,1.0,6.0,9
30153,2209060002,a_a000567,2,콩카페 롯데백화점 잠실점,2022-09-06,2022-09-06,서울 송파구 올림픽로 240,서울 송파구 잠실동 40-1,127.098572,37.511906,...,7.0,경기도,경기,2인 여행(가족 외),2022-09-06~2022-09-07,5.0,2.0,3.0,1.0,10

In [4]:
df_filter = df_filter[['GENDER', 'AGE_GRP', 'TRAVEL_STYL_1',
       'TRAVEL_STYL_2', 'TRAVEL_STYL_3', 'TRAVEL_STYL_4', 'TRAVEL_STYL_5',
       'TRAVEL_STYL_6', 'TRAVEL_STYL_7', 'TRAVEL_STYL_8','TRAVEL_MOTIVE_1',
       'TRAVEL_COMPANIONS_NUM', 'TRAVEL_MISSION_INT','VISIT_AREA_NM','DGSTFN']]

df_filter = df_filter.dropna()
df_filter

,GENDER,AGE_GRP,TRAVEL_STYL_1,TRAVEL_STYL_2,TRAVEL_STYL_3,TRAVEL_STYL_4,TRAVEL_STYL_5,TRAVEL_STYL_6,TRAVEL_STYL_7,TRAVEL_STYL_8,TRAVEL_MOTIVE_1,TRAVEL_COMPANIONS_NUM,TRAVEL_MISSION_INT,VISIT_AREA_NM,DGSTFN
0,남,30.0,4.0,4.0,2.0,4.0,6.0,5.0,6.0,6.0,1.0,0.0,5,프로방스마을,4.0
2,여,40.0,4.0,3.0,6.0,3.0,2.0,2.0,7.0,2.0,6.0,0.0,28,병점역 1호선,4.0
3,여,30.0,4.0,4.0,4.0,3.0,4.0,4.0,5.0,7.0,1.0,1.0,6,더현대서울,5.0
4,남,30.0,7.0,1.0,1.0,1.0,7.0,7.0,2.0,4.0,1.0,0.0,2,강릉중앙시장,4.0
5,남,20.0,6.0,1.0,1.0,3.0,4.0,6.0,3.0,2.0,3.0,1.0,11,청계천,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30145,여,30.0,3.0,1.0,3.0,3.0,4.0,4.0,7.0,6.0,1.0,0.0,3,행궁동벽화마을,2.0
30150,여,30.0,1.0,3.0,1.0,3.0,4.0,4.0,5.0,4.0,1.0,7.0,5,카페아쁠뤼스,5.0
30151,남,20.0,3.0,6.0,2.0,5.0,4.0,4.0,5.0,6.0,1.0,0.0,3,국립중앙박물관,5.0
30152,남,20.0,5.0,2.0,2.0,4.0,4.0,5.0,5.0,3.0,7.0,6.0,9,송도달빛축제공원,4.0
30153,여,20.0,4.0,1.0,2.0,2.0,2.0,4.0,2.0,7.0,5.0,1.0,10,콩카페 롯데백화점 잠실점,3.0

In [5]:
categorical_features_names = [
    'GENDER', 
    'TRAVEL_STYL_1',
       'TRAVEL_STYL_2', 'TRAVEL_STYL_3', 'TRAVEL_STYL_4', 'TRAVEL_STYL_5',
       'TRAVEL_STYL_6', 'TRAVEL_STYL_7', 'TRAVEL_STYL_8','TRAVEL_MOTIVE_1',
        'TRAVEL_MISSION_INT','VISIT_AREA_NM'
]
df_filter[categorical_features_names[1:-1]] = df_filter[categorical_features_names[1:-1]].astype(int)
df_filter

,GENDER,AGE_GRP,TRAVEL_STYL_1,TRAVEL_STYL_2,TRAVEL_STYL_3,TRAVEL_STYL_4,TRAVEL_STYL_5,TRAVEL_STYL_6,TRAVEL_STYL_7,TRAVEL_STYL_8,TRAVEL_MOTIVE_1,TRAVEL_COMPANIONS_NUM,TRAVEL_MISSION_INT,VISIT_AREA_NM,DGSTFN
0,남,30.0,4,4,2,4,6,5,6,6,1,0.0,5,프로방스마을,4.0
2,여,40.0,4,3,6,3,2,2,7,2,6,0.0,28,병점역 1호선,4.0
3,여,30.0,4,4,4,3,4,4,5,7,1,1.0,6,더현대서울,5.0
4,남,30.0,7,1,1,1,7,7,2,4,1,0.0,2,강릉중앙시장,4.0
5,남,20.0,6,1,1,3,4,6,3,2,3,1.0,11,청계천,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30145,여,30.0,3,1,3,3,4,4,7,6,1,0.0,3,행궁동벽화마을,2.0
30150,여,30.0,1,3,1,3,4,4,5,4,1,7.0,5,카페아쁠뤼스,5.0
30151,남,20.0,3,6,2,5,4,4,5,6,1,0.0,3,국립중앙박물관,5.0
30152,남,20.0,5,2,2,4,4,5,5,3,7,6.0,9,송도달빛축제공원,4.0
30153,여,20.0,4,1,2,2,2,4,2,7,5,1.0,10,콩카페 롯데백화점 잠실점,3.0

In [46]:
from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(df_filter, test_size=0.2, random_state=0)

In [49]:
df_filter.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14930 entries, 0 to 30153
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   GENDER                 14930 non-null  object
 1   AGE_GRP                14930 non-null  float64
 2   TRAVEL_STYL_1          14930 non-null  int32
 3   TRAVEL_STYL_2          14930 non-null  int32
 4   TRAVEL_STYL_3          14930 non-null  int32
 5   TRAVEL_STYL_4          14930 non-null  int32
 6   TRAVEL_STYL_5          14930 non-null  int32
 7   TRAVEL_STYL_6          14930 non-null  int32
 8   TRAVEL_STYL_7          14930 non-null  int32
 9   TRAVEL_STYL_8          14930 non-null  int32
 10  TRAVEL_MOTIVE_1        14930 non-null  int32
 11  TRAVEL_COMPANIONS_NUM  14930 non-null  float64
 12  TRAVEL_MISSION_INT     14930 non-null  int32
 13  VISIT_AREA_NM          14930 non-null  object
 14  DGSTFN                 14930 non-null  float64
dtypes: float64(3), int32(10), object(2)
memory usage: 1.3+ MB

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# 범주형 데이터를 숫자로 변환
label_encoders = {}
for column in ['GENDER', 'VISIT_AREA_NM']:
    label = LabelEncoder()
    df_filter[column] = label.fit_transform(df_filter[column])
    label_encoders[column] = label

# 특징과 타겟 변수 분리
x = df_filter.drop('DGSTFN', axis=1)[:10000]
y = df_filter['DGSTFN'][:10000]

# 학습용 데이터와 테스트용 데이터 분리
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state= 0)

# 모델 리스트
models = {
    'Random Forest': RandomForestClassifier(n_estimators=10, random_state= 0),
    'Logistic Regression': LogisticRegression(),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(n_estimators=10, random_state= 0)
}

# 모델 학습 및 평가
for name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f'{name} 모델 정확도: {accuracy:.4f}')

Random Forest 모델 정확도: 0.5215

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression 모델 정확도: 0.4675
K-Nearest Neighbors 모델 정확도: 0.4020
Gradient Boosting 모델 정확도: 0.4900

In [7]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import pandas as pd


x = df_filter.drop('DGSTFN', axis=1)[:10000]
y = df_filter['DGSTFN'][:10000]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

# 수치형 특징과 범주형 특징 분리
numeric_features = x_train.select_dtypes(include=['int32', 'float64']).columns.tolist()
categorical_features = ['GENDER', 'VISIT_AREA_NM']

# 전처리 파이프라인
# 수치형 -> 표준화
numeric_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])
# 범주형 -> 원핫인코딩
categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# ColumnTransformer -> 여러 종류의 전처리 작업을 서로 다른 열에 적용할 수 있도록 도와줌
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# 모델 리스트
models = {
    'Random Forest': RandomForestClassifier(random_state=0),
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(random_state=0)
}

# 하이퍼파라미터 튜닝 및 모델 학습
best_models = {}
for name, model in models.items():
    pipeline = Pipeline(steps=[('preprocessor', preprocessor), ('classifier', model)])
    
    if name == 'Random Forest':
        param_grid = {
            'classifier__n_estimators': [50, 100, 200],
            'classifier__max_depth': [None, 10, 20]
        }
    elif name == 'Logistic Regression':
        param_grid = {
            'classifier__C': [0.01, 0.1, 1, 10]
        }
    elif name == 'K-Nearest Neighbors':
        param_grid = {
            'classifier__n_neighbors': [3, 5, 7],
            'classifier__weights': ['uniform', 'distance']
        }
    elif name == 'Gradient Boosting':
        param_grid = {
            'classifier__n_estimators': [50, 100, 200],
            'classifier__learning_rate': [0.01, 0.1, 0.2]
        }
    
    grid_search = GridSearchCV(pipeline, param_grid, cv=3, n_jobs=-1)
    grid_search.fit(x_train, y_train)
    best_models[name] = grid_search.best_estimator_
    y_pred = grid_search.predict(x_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f'{name} 모델 정확도: {accuracy:.4f}')

# 최종 모델 선택 및 평가
for name, model in best_models.items():
    y_pred = model.predict(x_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f'{name} 최적화된 모델 정확도: {accuracy:.4f}')

Random Forest 모델 정확도: 0.5660
Logistic Regression 모델 정확도: 0.4505
K-Nearest Neighbors 모델 정확도: 0.5260
Gradient Boosting 모델 정확도: 0.4910
Random Forest 최적화된 모델 정확도: 0.5660
Logistic Regression 최적화된 모델 정확도: 0.4505
K-Nearest Neighbors 최적화된 모델 정확도: 0.5260
Gradient Boosting 최적화된 모델 정확도: 0.4910

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

# 피처와 타겟 정의
x = df_filter.drop('DGSTFN', axis=1)
y = df_filter['DGSTFN']

# 데이터 분할
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

# 수치형 특징과 범주형 특징 분리
numeric_features = x_train.select_dtypes(include=['int32', 'float64']).columns.tolist()
categorical_features = ['GENDER', 'VISIT_AREA_NM']

# 전처리 파이프라인 구성
numeric_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])
categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# 랜덤 포레스트 모델 정의 및 하이퍼파라미터 튜닝
model = RandomForestClassifier(random_state=0)
param_grid = {
    'classifier__n_estimators': [50, 100, 200],
    'classifier__max_depth': [None, 10, 20]
}
pipeline = Pipeline(steps=[('preprocessor', preprocessor), ('classifier', model)])
grid_search = GridSearchCV(pipeline, param_grid, cv=3, n_jobs=-1)

# 모델 학습
grid_search.fit(x_train, y_train)

# 최적 모델 선택 및 평가
best_model = grid_search.best_estimator_
y_pred = best_model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'랜덤 포레스트 최적화된 모델 정확도: {accuracy:.4f}')

랜덤 포레스트 최적화된 모델 정확도: 0.5754

In [6]:
area_names = df_filter[['VISIT_AREA_NM']].drop_duplicates()
len(area_names)

8710

In [7]:
area_names

      VISIT_AREA_NM
0            프로방스마을
2           병점역 1호선
3             더현대서울
4            강릉중앙시장
5               청계천
...             ...
30128       설악버스터미널
30136      탄도어촌체험마을
30138      하남ICEBOX
30141       부평역사박물관
30150        카페아쁠뤼스

[8710 rows x 1 columns]

In [14]:
x_test.shape

(2986, 14)

In [15]:
x_test.iloc[1987].to_dict(), y_test.iloc[1987]

({'GENDER': 1.0,
  'AGE_GRP': 30.0,
  'TRAVEL_STYL_1': 2.0,
  'TRAVEL_STYL_2': 5.0,
  'TRAVEL_STYL_3': 3.0,
  'TRAVEL_STYL_4': 7.0,
  'TRAVEL_STYL_5': 2.0,
  'TRAVEL_STYL_6': 2.0,
  'TRAVEL_STYL_7': 7.0,
  'TRAVEL_STYL_8': 6.0,
  'TRAVEL_MOTIVE_1': 1.0,
  'TRAVEL_COMPANIONS_NUM': 1.0,
  'TRAVEL_MISSION_INT': 6.0,
  'VISIT_AREA_NM': 901.0},
 5.0)

In [10]:
df_filter = df_filter.dropna()

In [11]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

# 예제 데이터
area_names = pd.DataFrame({'VISIT_AREA_NM': ['Area1', 'Area2', 'Area3']})

# 피처와 타겟 정의
# df_filter는 학습에 사용한 DataFrame으로 가정
x = df_filter.drop('DGSTFN', axis=1)
y = df_filter['DGSTFN']

# 데이터 분할
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

# 수치형 특징과 범주형 특징 분리
numeric_features = x_train.select_dtypes(include=['int32', 'float64']).columns.tolist()
categorical_features = ['GENDER', 'VISIT_AREA_NM']

# 전처리 파이프라인 구성
numeric_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])
categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# 랜덤 포레스트 모델 정의 및 하이퍼파라미터 튜닝
model = RandomForestClassifier(random_state=0)
param_grid = {
    'classifier__n_estimators': [50, 100, 200],
    'classifier__max_depth': [None, 10, 20]
}
pipeline = Pipeline(steps=[('preprocessor', preprocessor), ('classifier', model)])
grid_search = GridSearchCV(pipeline, param_grid, cv=3, n_jobs=-1)

# 모델 학습
grid_search.fit(x_train, y_train)

# 최적 모델 선택 및 평가
best_model = grid_search.best_estimator_
y_pred = best_model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'랜덤 포레스트 최적화된 모델 정확도: {accuracy:.4f}')

# 새로운 입력 데이터 예측
traveler = {'GENDER': 1.0,
  'AGE_GRP': 30.0,
  'TRAVEL_STYL_1': 2.0,
  'TRAVEL_STYL_2': 5.0,
  'TRAVEL_STYL_3': 3.0,
  'TRAVEL_STYL_4': 7.0,
  'TRAVEL_STYL_5': 2.0,
  'TRAVEL_STYL_6': 2.0,
  'TRAVEL_STYL_7': 7.0,
  'TRAVEL_STYL_8': 6.0,
  'TRAVEL_MOTIVE_1': 1.0,
  'TRAVEL_COMPANIONS_NUM': 1.0,
  'TRAVEL_MISSION_INT': 6.0,
  'VISIT_AREA_NM': 'Area1'  # 초기 값은 임의의 값으로 설정
}

results = pd.DataFrame([], columns=['AREA', 'SCORE'])

for area in area_names['VISIT_AREA_NM']:
    traveler['VISIT_AREA_NM'] = area
    input_data = pd.DataFrame([traveler])
    
    # 전처리 및 예측
    input_data_transformed = best_model.named_steps['preprocessor'].transform(input_data)
    score = best_model.named_steps['classifier'].predict(input_data_transformed)
    
    results = pd.concat([results, pd.DataFrame([[area, score[0]]], columns=['AREA', 'SCORE'])])

# 결과 정렬 및 상위 10개 출력
results = results.sort_values('SCORE', ascending=False).head(10)
print(results)

랜덤 포레스트 최적화된 모델 정확도: 0.5710

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''